"""remove f_column again

Revision ID: a751abfe078c
Revises: 5a25c8ba7b52
Create Date: 2023-04-29 18:16:17.988139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751abfe078c'
down_revision = '5a25c8ba7b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
